package com.sanitova.sanitovacheck

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Locale

/**
 * Generates a simple, professional-looking PDF compliance report
 * from an AssessResponse, saves it to app cache, and returns a
 * shareable content:// Uri via FileProvider.
 */
object PdfReportGenerator {

    private const val PAGE_WIDTH = 595  // A4 at 72dpi
    private const val PAGE_HEIGHT = 842
    private const val MARGIN = 48f

    fun generate(context: Context, caseId: String, result: AssessResponse): Uri {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, 1).create()
        val page = document.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        var y = MARGIN

        val titlePaint = Paint().apply {
            color = Color.rgb(30, 30, 30)
            textSize = 22f
            isFakeBoldText = true
        }
        val subtitlePaint = Paint().apply {
            color = Color.rgb(90, 90, 90)
            textSize = 11f
        }
        val headingPaint = Paint().apply {
            color = Color.rgb(20, 20, 20)
            textSize = 14f
            isFakeBoldText = true
        }
        val bodyPaint = Paint().apply {
            color = Color.rgb(40, 40, 40)
            textSize = 12f
        }
        val riskColor = when (result.assessment.riskLevel.lowercase()) {
            "high" -> Color.rgb(198, 40, 40)
            "medium" -> Color.rgb(191, 144, 0)
            else -> Color.rgb(46, 125, 50)
        }
        val riskPaint = Paint().apply {
            color = riskColor
            textSize = 18f
            isFakeBoldText = true
        }

        // Header
        canvas.drawText("SanitovaCheck Compliance Report", MARGIN, y, titlePaint)
        y += 26f
        canvas.drawText(
            "Generated ${SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.US).format(java.util.Date())}",
            MARGIN, y, subtitlePaint
        )
        y += 16f
        canvas.drawText("Case ID: $caseId", MARGIN, y, subtitlePaint)
        y += 30f

        canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, Paint().apply {
            color = Color.rgb(220, 220, 220)
        })
        y += 30f

        // Risk level
        canvas.drawText(
            "Risk Level: ${result.assessment.riskLevel.uppercase()}  (Score: ${result.assessment.riskScore}/10)",
            MARGIN, y, riskPaint
        )
        y += 34f

        // Summary
        canvas.drawText("Summary", MARGIN, y, headingPaint)
        y += 18f
        y = drawWrappedText(canvas, result.assessment.summary, MARGIN, y, bodyPaint, PAGE_WIDTH - 2 * MARGIN)
        y += 20f

        // Key concerns
        canvas.drawText("Key Concerns", MARGIN, y, headingPaint)
        y += 18f
        result.assessment.keyConcerns.forEach { concern ->
            y = drawWrappedText(canvas, "• $concern", MARGIN, y, bodyPaint, PAGE_WIDTH - 2 * MARGIN)
            y += 4f
        }
        y += 16f

        // Recommended action
        canvas.drawText("Recommended Action", MARGIN, y, headingPaint)
        y += 18f
        val actionText = result.assessment.recommendedAction
            .replace("_", " ")
            .replaceFirstChar { it.uppercase() }
        canvas.drawText(actionText, MARGIN, y, bodyPaint)
        y += 20f

        canvas.drawText("Assigned to: ${result.routing.assignTo.replace("_", " ")}", MARGIN, y, bodyPaint)
        y += 16f
        canvas.drawText("Response window: ${result.routing.slaHours} hours", MARGIN, y, bodyPaint)
        y += 40f

        // Footer disclaimer
        val disclaimerPaint = Paint().apply {
            color = Color.rgb(130, 130, 130)
            textSize = 9f
        }
        y = drawWrappedText(
            canvas,
            "This report is an AI-assisted self-assessment tool and does not replace an official " +
                "inspection by a licensed Environmental Health Officer. Generated by SanitovaCheck " +
                "(Sanitova Environmental Health Services Ltd).",
            MARGIN, PAGE_HEIGHT - MARGIN - 20f, disclaimerPaint, PAGE_WIDTH - 2 * MARGIN
        )

        document.finishPage(page)

        val fileName = "SanitovaCheck_Report_$caseId.pdf"
        val file = File(context.cacheDir, fileName)
        FileOutputStream(file).use { out ->
            document.writeTo(out)
        }
        document.close()

        return FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
    }

    /**
     * Simple word-wrap: draws text within maxWidth, returns the y position after the last line.
     */
    private fun drawWrappedText(
        canvas: Canvas,
        text: String,
        x: Float,
        startY: Float,
        paint: Paint,
        maxWidth: Float
    ): Float {
        var y = startY
        val words = text.split(" ")
        var line = StringBuilder()

        for (word in words) {
            val testLine = if (line.isEmpty()) word else "$line $word"
            if (paint.measureText(testLine) > maxWidth) {
                canvas.drawText(line.toString(), x, y, paint)
                y += paint.textSize + 4f
                line = StringBuilder(word)
            } else {
                line = StringBuilder(testLine)
            }
        }
        if (line.isNotEmpty()) {
            canvas.drawText(line.toString(), x, y, paint)
            y += paint.textSize + 4f
        }
        return y
    }
}
